# --- !Ups

CREATE SCHEMA irm;

DROP TABLE IF EXISTS incidents;
CREATE TABLE incidents (
	id 					integer			NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title 				varchar(256)	NOT NULL,
	description 		TEXT			NOT NULL,
	incident_type		varchar(127)	NOT NULL,
	status				varchar(127)	NOT NULL,
	issue_id			varchar(64),
	issue_type_id		integer,	
	respond_team_id		integer,
	primary_responder 	integer  			NOT NULL,
	started_at			DATETIME,
	finished_at			DATETIME,
	next_update_at		DATETIME,
	created_at			DATETIME		NOT NULL,
	updated_at			DATETIME		NOT NULL,
	created_by			integer			NOT NULL,
	updated_by			integer,
	PRIMARY KEY (id)
);



DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id 					integer          	NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	first_name			varchar(127)	NOT NULL,
	last_name			varchar(127)	NOT NULL,
	email				varchar(255)	NOT NULL,
	deleted 			Boolean 		NOT NULL,
	PRIMARY KEY(id),
	UNIQUE (email)
);


DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
	id 					integer			NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name 				varchar(127)	NOT NULL,
	deleted 			Boolean 		NOT NULL,
	PRIMARY KEY(id),
	UNIQUE(name)
);


DROP TABLE IF EXISTS user_team_map;
CREATE TABLE user_team_map (
	user_id				integer			NOT NULL,
	team_id  			integer			NOT NULL,
	PRIMARY KEY (user_id, team_id)
);

DROP TABLE IF EXISTS incident_updates;
CREATE TABLE incident_updates (
	id  				integer			NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	incident_id			integer            NOT NULL,
	description			TEXT 			NOT NULL,
	created_by			integer			NOT NULL,
	created_at			DATETIME		NOT NULL,
	deleted				BOOLEAN 		NOT NULL,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS incident_subscriptions;
CREATE TABLE incident_subscriptions (
	incident_id			integer			NOT NULL,
	team_id 			integer			NOT NULL,
	PRIMARY KEY(incident_id, team_id)
);


DROP TABLE IF EXISTS issue_types;
CREATE TABLE issue_types (
	id					integer			NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	slug				varchar(127)	NOT NULL,
	clazz				varchar(256),
	name 				varchar(256),
	PRIMARY KEY(id),
	UNIQUE(slug)
);

INSERT INTO issue_types VALUES(1, 'direct', null, 'Direct');
INSERT INTO issue_types VALUES(2, 'jira', null, 'JIRA');
INSERT INTO issue_types VALUES(3, 'pager-duty', null, 'Pager Duty');

# --- !Downs